-- CREATE TABLE ACCOUNT_BOOK(
-- 	ACCOUNT_BOOK_ID SERIAL PRIMARY KEY,  -- 帳本編號
-- 	ACCOUNT_BOOK_NAME VARCHAR(30) NOT NULL,  -- 帳本名稱
-- 	DESCRIPTION VARCHAR(50),  -- 帳本敘述
-- 	BASE_CURRENCY VARCHAR(5),  -- 帳本貨幣別
--  OWNER INTEGER  -- 帳本所有人
-- );

ALTER TABLE ACCOUNT_BOOK
ADD COLUMN owner INTEGER;