-- CREATE TABLE TRANSACTION(
-- 	TRANSACTION_ID SERIAL PRIMARY KEY,  -- 交易編號
-- 	ACCOUNT_BOOK_ID INTEGER,  -- 帳本編號
-- 	DATE TIMESTAMP,  -- 交易日期
-- 	AMOUNT INTEGER,  -- 交易金額
-- 	DESCRIPTION VARCHAR(100),  -- 交易敘述
-- 	TRANSACTION_CURRENCY VARCHAR(5),  -- 交易貨幣別
-- 	CATEGORY VARCHAR(10)  -- 交易類別
-- );


-- ALTER TABLE TRANSACTION
-- ADD COLUMN ACCOUNT_BOOK_ID INTEGER;

-- ALTER TABLE TRANSACTION
-- ADD COLUMN INCLUDE_IN_BUDGET BOOL;